### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by markus-seidl** [brainboutique/raml-typescript-generator#3]
Got this problem while running the generator against a sample file:

```
Processing done. Please update package.json with custom data! At any time, run 'npm run regen' to update based on updated RAML file.
TypeError: Cannot read property 'length' of undefined
    at Object.default_1 [as src/index.ts] (/usr/local/lib/node_modules/raml-typescript-generator/dist/templates/src/index.ts.js:48:47)
    at /usr/local/lib/node_modules/raml-typescript-generator/node_modules/raml-generator/dist/index.js:13:36
    at Array.forEach (native)
    at defaultGenerate (/usr/local/lib/node_modules/raml-typescript-generator/node_modules/raml-generator/dist/index.js:12:28)
    at /usr/local/lib/node_modules/raml-typescript-generator/node_modules/raml-generator/dist/index.js:5:21
    at /usr/local/lib/node_modules/raml-typescript-generator/node_modules/raml-generator/dist/bin.js:31:36
    at <anonymous>
```

**Comment by denisoby** [comment]
I've got the same problem. This happens in line 
> for (var _i = 0, _a = api.schemas; _i < _a.length; _i++) {

**Comment by michalzubkowicz** [comment]
This problem makes project unusable. It seems abandoned.
